version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: rust_web_handson_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: web_handson
      TZ: Asia/Tokyo
    command:
      [
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --default-authentication-plugin=mysql_native_password,
      ]
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
  mock:
    image: rodolpheche/wiremock:latest-alpine
    volumes:
      - "./wiremock:/home/wiremock"
    ports:
      - 18080:8080
    restart: on-failure
